apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  name: "appsvc"
  namespace: "octank-dev"
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    app: "appsvc"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsvc
  namespace: octank-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: appsvc
  template:
    metadata:
      labels:
        app: appsvc
    spec:
      containers:
        - name: appsvc
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
        - 
          image: "amazon/aws-xray-daemon:latest"
          imagePullPolicy: Always
          name: xray-sidecar
          ports: 
            - 
              containerPort: 2000
              name: xray-ingest
              protocol: UDP
          resources: 
            limits: 
              memory: 24Mi
          volumeMounts: 
            - 
              mountPath: /aws/xray
              name: config-volume
              readOnly: true
      serviceAccountName: xray-daemon
      volumes: 
        - 
          configMap: 
            name: xray-config
          name: config-volume