apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  name: "coveragesvc"
  namespace: "octank-dev"
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    app: "coveragesvc"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coveragesvc
  namespace: octank-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: coveragesvc
  template:
    metadata:
      labels:
        app: coveragesvc
    spec:
      containers:
        - name: coveragesvc
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
        - 
          image: "amazon/aws-xray-daemon:latest"
          imagePullPolicy: Always
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            runAsUser: 0          
          name: xray-sidecar
          ports: 
            - 
              containerPort: 2000
              name: xray-ingest
              protocol: UDP
          resources: 
            limits: 
              memory: 24Mi
          volumeMounts: 
            - 
              mountPath: /aws/xray
              name: config-volume
              readOnly: true
      serviceAccountName: xray-daemon
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - coveragesvc
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
      
      volumes: 
        - 
          configMap: 
            name: xray-config
          name: config-volume